### ISSUE TITLE
run_exports?

### ISSUE THREAD

**Issue by AaronOpfer** [conda-forge/blis-feedstock#37]
### Comment:

Would it be appropriate to add `run_exports` to this package, such that depending on this package in `host` automatically adds a dependency to it in `run`?

**Comment by gdonval** [comment]
Not really no. 

Beyond the damage that `run_exports` misuse does to conda, `blis` is only one-of-many BLAS implementation. It is therefore never ever a good idea to hardcode `blis` in your recipes.

If you know you need the full range of BLAS/LAPACK/etc. libraries, you need to put the `blas` package in `host`. If you know you only need e.g. BLAS, you only have to specify `libblas` instead. At installation time, your package's user can then choose the specific blas implementation they want. Any of those actions will capture the correct runtime dependencies and do basically what you ask.
